# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('choice_correct', models.CharField(max_length=100)),
                ('choice1', models.CharField(max_length=100)),
                ('choice2', models.CharField(max_length=100)),
                ('choice3', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('EASY', 'easy type'), ('HARD', 'hard type')], default='EASY', max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ncqs.Questions'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
